#!/usr/bin/env bash

##############################################################################
##
##  Gradle start script for POSIX generated by Gradle.
##
##  IMPORTANT: Do not modify this file as it will be overwritten by Gradle.
##
##  This script expects to find the wrapper JAR file in the same directory
##  as this script.
##
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME="${app_path%/*}"
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link="${ls#*' -> '}"
    case "$link" in             #(
      /*)   app_path="$link" ;; #(
      *)    app_path="$APP_HOME/$link" ;;
    esac
done

# Change to the directory of the script
cd "${APP_HOME}" || die "Could not change directory to $APP_HOME"

# Start the gradle wrapper
exec java -jar gradle/wrapper/gradle-wrapper.jar "$@"
