#!/bin/bash
echo "Preparing project for GitHub upload..."
echo "Checking project structure..."
find . -name "*.kt" -o -name "*.xml" -o -name "*.gradle" -o -name "AndroidManifest.xml" | head -20

echo -e "\nCreating .gitignore..."
cat > .gitignore << EOF
# Android
*.iml
*.ipr
*.iws
.idea/
.gradle/
local.properties
captures/
.externalNativeBuild
.cxx/
*.keystore
*.jks

# Built application files
*.apk
*.aar
*.so

# Files for the ART/Dalvik VM
*.dex

# Local configuration file (sdk path, etc)
local.properties

# Log Files
*.log

# Android Studio Navigation editor temp files
.navigation/

# Android Coverage
coverage/
*.ec

# Firebase emulators
.firebase/

# Built tool files
*/build/
!gradle/wrapper/gradle-wrapper.jar

# Android Profiling
*.har
.hprof.txt

# Leaked properties files
*.properties

# Proguard folder generated by New Relic
proguard/

# Logcat from Android Studio
exported_log_files/

# Android sneaky files
Thumbs.db
.DS_Store
.git
EOF

echo "Setup complete! Now follow these steps:"
echo "1. git init"
echo "2. git add ."
echo "3. git commit -m \"Initial commit\""
echo "4. Create a new repository on GitHub"
echo "5. git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git"
echo "6. git branch -M main"
echo "7. git push -u origin main"
echo ""
echo "After pushing, GitHub Actions will build your APK automatically!"
